CREATE SEQUENCE s_seq
INCREMENT BY 1
START WITH 1
MAXVALUE 100; //버전이 올라가서 접근 제안이 생긴거

SELECT min_value, max_value, increment_by, last_number
FROM user_sequences
WHERE sequence_name = 'S_SEQ';//데이터 사전은 무조건 대문자로 찾기

DESC emp;
insert into emp(empno, ename, job, deptno)
values(S_SEQ.NEXTVAL, 'CANDY', 'SALESMAN', 20);

insert into emp(empno, ename, job, deptno)
values(S_SEQ.NEXTVAL, 'CANDY10', 'SALESMAN', 20);

insert into emp(empno, ename, job, deptno)
values(S_SEQ.NEXTVAL, 'CANDY20', 'SALESMAN', 20);

select * from emp;

select S_SEQ.CURRVAL
from DUAL;

select S_SEQ.NEXTVAL
from DUAL;

alter sequence s_seq maxvalue 200;

drop sequence s_seq;

CREATE SEQUENCE member_seq
START WITH 1
INCREMENT BY 1;

create table member(
                    id number generated by default as identity,
                    name varchar2(100)
                    );
                    
insert into member(name)
values ('홍길동');

insert into member(name)
values ('홍길순');

select * from member;

//테이블 관리
//테이블 생성
create table address
(id number(3),
name varchar2(50),
addr varchar2(100),
phone varchar2(30),
email varchar2(100));

select * from tab;// 모든 테이블이 나옴
desc address;

insert into address
values (1, 'HGDONG', 'SEOUL', '123-4567', 'gdhong@cwunet.ac.kr');

commit;
select * from address;//들어갔는지 확인

//made by sub query 
create table addr_second(id, name, addr, phone, e_mail)
as select * from address;
desc addr_second;

//테이블 구조 복사
create table addr_fourth
as select id, name from address
where 1=2;
desc addr_fourth;
select * from addr_fourth;

//subquery 생성
create table addr_third
as select id, name from address;
desc addr_third;

alter table address
add (birth date);

alter table address
add(comments varchar2(200) default 'No Comment');

select * from address;

insert into address(id, name, addr)
values (2, 'hr', '서울');

//DROP
ALTER TABLE address drop column comments;

//column change = modify
alter table address
modify phone varchar2(50);

desc address;

//rename
rename addr_second to client_address;
desc addr_second;
desc client_address;

//drop table
select * from tab;
drop table addr_third;

//truncate
truncate table client_address;
select * from client_address;
rollback;

//comment
comment on table address
is  '고객 주소록 관리하시 위한 테이블';

comment on column address.name
is  '고객이름';

//주석확인하는 방법
select comments
from user_tab_comments
where table_name = 'ADDRESS';

//컬럼주석확인하는 방법
select *
from user_col_comments
where table_name = 'ADDRESS';

//주석 삭제하는 것
comment on table address is  '';
comment on column address.name is  '';//컬럼

//데이터 사전
--user_tables
select table_name from user_tables;

--all_tables
select owner, table_name from all_tables;

//dea_tables
select owner, table_name from dba_tables;

//테이블 정보조회
select table_name, tablespace_name, min_extents, max_extents
from user_tables
where table_name like 'ADDR%';

//오브젝트 조회
select object_name, object_type, created
from user_objects
where object_name like 'ADDR%' and object_type = 'TABLE';

//카탈로그 조회
select * from user_catalog;

//데이터 무결성
//데이터 무결성 생성
--과목 테이블 인스턴스
create table subject
(subno number(5)
       constraint subject_no_pk primary key
       deferrable initially deferred
       using index tablespace indxx,
subname varchar2(20)
        constraint subject_name_nn not null,
term varchar2(1)
     constraint subject_term_ck check (term in ('1','2')),
type varchar2(6));

create tablespace indxx
datafile 'C:\app\kosa\product\21c\oradata\XE\indxx.dbf' size 100m;

desc subject;
desc emp;

--수강 테이블 인스턴스
alter table student 
add constraint stud_no_pk primary key(studno);

select * from student;
delete from student where studno = 33333;
commit;

create table sugang
(studno number(5)
        constraint sugang_studno_fk references student(studno),
subno   number(5)
        constraint sugang_subno_fk references subject(subno),
regdate date,
result  number(3),
        constraint sugang_pk primary key(studno,subno));
desc sugang;

//무결성 제약조건 조회
select constraint_name, constraint_type
from user_constraints
where table_name in ('SUBJECT', 'SUGANG');

--무결성 제약조건 추가
alter table student
add constraint stud_idnum_uk unique(idnum);

alter table student
modify (name constraint stud_name_nn not null);

alter table student add constraint stud_deptno_fk
foreign key(deptno) references department(deptno);//부모가 한명으로 유일해야지 들어갈 수 있음
alter table department add constraint dept_pk primary key(deptno);


//실습1
desc department;
alter table department modify (dname not null);

//실습2
alter table professor add constraint prof_pk primary key(profno);

alter table professor modify (name not null);

alter table professor add constraint prof_fk
foreign key(deptno) references department(deptno);

//제약조건에 위배되는 데이터 입력의 경우
insert into subject values(1, 'SQL', '1', '필수');

commit;
select * from subject;
//지연조건에 위배되는 데이터 입력의 경우
insert into subject values(4, '데이터베이스', '1', '필수');
insert into subject values(4, '데이터모델링', '2', '선택');
commit;

//무결성 제약조건 삭제시
select constraint_name, constraint_type
from user_constraints
where table_name = 'SUBJECT';

alter table subject
drop constraint subject_term_ck;

//무결성 제약조건 비활성화
alter table sugang
disable constraint sugang_pk;

alter table sugang
disable constraint sugang_studno_fk;

select constraint_name, status
from user_constraints
where table_name in ('SUGANG', 'SUBJECT');

//ENABLE
alter table sugang
enable constraint sugang_pk;

alter table sugang
enable constraint sugang_studno_fk;

select constraint_name, status
from user_constraints
where table_name = 'SUGANG';

//제약조건 조회
select table_name, constraint_name, constraint_type, status
from user_constraints
where table_name in ('STUDENT', 'PROFESSOR', 'DEPARTMENT');

select table_name, column_name, constraint_name
from user_cons_columns
where table_name in ('STUDENT', 'PROFESSOR', 'DEPARTMENT');

/*문제1[시퀀스를 먼저 생성하고 만들면 employee_id를 1씩 증가하게 만들 수 있다. ]
아래와 같이 EMPLOYEE테이블을 생성하세요.
EMPLOYE_ID는 PRIMARY KEY, NAME은 NOT NULL
Name        Null        Type
-------- ------------- ------------
EMPLOYEE_ID             NUMBER(7)
NAME                    VARCHAR2(25)
ADDRESS                 VARCHAR2(25)
DEPTNO                  NUMBER(2)
PHONE_NUMBER            VARCHAR2(20)
*/
create sequence emp_seq
increment by 1
start with 1
maxvalue 9999999;

--Table EMPLOYEE이(가) 생성되었습니다.
create table employee (
    employee_id  number(7) default emp_seq.nextval,
    name         varchar2(25) not null,
    address      varchar2(25),
    deptno       number(2),
    phone_number varchar2(20),
    constraint employee_pk primary key(employee_id)
);
--Table EMPLOYEE이(가) 생성되었습니다.

desc employee;

/*문제2
1번에서 생성한 테이블에 아래와 같이 4건의 데이터를 입력하세요
*/
insert into employee values(1111111,'MAYBELL','SEOUL',10,'123-4567');
insert into employee values(0000000,'BELLY','SEOUL',20,'234-5678');
insert into employee values(2222222,'COUGH','INCHEAN',30,'345-6789');
insert into employee values(3333333,'DILLY','SEOUL',40,'012-3456');

select * from employee;


/*문제3
위에서 생성된 EMPLOYEE 테이블의 DEPTNO는 DEPTNO칼럼을 참조하게 제약조건을 설정해보세요
*/
alter table employee add constraint employee_deptno_fk
foreign key(deptno) references dept(deptno);

/*문제4
INSERT INTO employee(name, deptno)
values('BENJAMIN', 50);
데이터를 입력하려 하였으나 실패한 이유는
*/
--일단은 employee_id의 primary key가 지정되지 않았고, 
--dept테이블에 있는 값이 deptno에 있는 값이 10,20,30,40이기 때문이다. 

/*문제5
생성한 EMPLOYEE테이블을 삭제하세요.
*/
drop table employee;
drop sequence emp_seq;
drop sequence e_seq;